# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

ng_pseudo_response_rcpp <- function(x, w = as.numeric( c())) {
    .Call(`_outrigger_ng_pseudo_response_rcpp`, x, w)
}

